[build]
builder = "nixpacks"
buildCommand = "npm run build && php artisan optimize"

[deploy]
startCommand = "touch /app/storage/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
