name: Laravel Tests

on:
  push:
    branches: ["master", "main"]
  pull_request:

env:
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: gd, intl, zip, sqlite3

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Create SQLite database file for migration step
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Key
        run: php artisan key:generate --force

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Restore bun install cache
        id: cache-bun-install
        uses: actions/cache@v4


        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun Dependencies and Build Assets
        run: bun install && bun run build

      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test

      - name: Execute migrations
        run: php artisan migrate:fresh --force

      - name: Execute seeders
        run: php artisan db:seed FakeDataSeeder --force
